version: '2.4'

services:
  postgres:
    image: topaztechnology/topaz-postgres:11.9
    hostname: postgres
    restart: always
    # Uncomment to expose Postgres externally
    #ports:
    #- 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      TOPAZ_PASSWORD: topaz

  monet:
    image: topaztechnology/monetdb:11.31.13
    hostname: monet
    restart: always
    # Uncomment to expose Monet externally
    #ports:
    #- 50000:50000
    volumes:
    - monet-data:/var/lib/monetdb
    - topaz-shared:/opt/topaz/tmp
    environment:
      LOG_LEVEL: INFO
      MONET_DATABASE: topaz-pivot

  topaz:
    image: topaztechnology/topaz:latest
    hostname: topaz
    restart: always
    mem_limit: 6gb
    ports:
    - 9021:9021    # Getdown port
    - 26634:26634  # Topaz server port
    # Uncomment to expost REPL port locally
    #- 127.0.0.1:26636:26636
    volumes:
    - topaz-conf:/opt/topaz/conf
    - topaz-data:/opt/topaz/data
    - topaz-log:/opt/topaz/log
    - topaz-shared:/opt/topaz/tmp
    environment:
      LOG_LEVEL: INFO
      TOPAZ_START_ARGS: com.topaz.server.Main
      AKKA_DISCOVERY_TYPE: config
      JVM_NAME: Seed
      # Set first time only using bin/create-password-hash.sh. Remember to quote and replace $ with $$
      # This example has a password of "root" and must be changed
      ROOT_PASSWORD_HASH: "$$2a$$12$$FMN3DQ5DeF06gLw/yb3WsegCTSExXb34g6mdLp8ctD6GaKK80VvpO"
      # Set this initially here or in config and never change.
      # This example hashing pepper must be changed
      PASSWORD_HASHING_PEPPER: "pepper"
    depends_on:
    - postgres
    - monet

  topaz-compute-1:
    image: topaztechnology/topaz:latest
    hostname: topaz-compute-1
    restart: always
    mem_limit: 6gb
    volumes:
    - topaz-conf:/opt/topaz/conf
    - topaz-log:/opt/topaz/log
    environment:
      TOPAZ_START_ARGS: com.topaz.server.ComputeMain
      AKKA_DISCOVERY_TYPE: config
      JVM_NAME: Compute-1
    depends_on:
    - topaz

  topaz-compute-2:
    image: topaztechnology/topaz:latest
    hostname: topaz-compute-2
    restart: always
    mem_limit: 6gb
    volumes:
    - topaz-conf:/opt/topaz/conf
    - topaz-log:/opt/topaz/log
    environment:
      TOPAZ_START_ARGS: com.topaz.server.ComputeMain
      AKKA_DISCOVERY_TYPE: config
      JVM_NAME: Compute-2
    depends_on:
    - topaz
  
volumes:
  postgres-data:
  monet-data:
  topaz-data:
  topaz-log:
  topaz-shared:
  topaz-conf:
    external: true
