version: '3'

services:
  sqlserver:
    image: topaztechnology/mssql-server-linux:2019-CU4
    hostname: sqlserver
    restart: always
    # Uncomnment to expose SQL Server externally
    #ports:
    #- 1433:1433
    volumes:
    - sqlserver-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SQL_USER: topaz
      SQL_PASSWORD: topaz
      SQL_DB: TopazMain

  redis:
    image: topaztechnology/redis:4.0.2
    hostname: redis
    restart: always
    # Uncomment to expose Redis externally
    #ports:
    #- 6379:6379
    volumes:
    - redis-data:/redis/data
    environment:
      LOG_LEVEL: INFO
      REDIS_TYPE: server

  monet:
    image: topaztechnology/monetdb:11.37.11
    hostname: monet
    restart: always
    mem_limit: 1gb
    # Uncomment to expose Monet externally
    #ports:
    #- 50000:50000
    volumes:
    - monet-data:/var/lib/monetdb
    - topaz-shared:/opt/topaz/tmp
    environment:
      LOG_LEVEL: INFO
      MONET_DATABASE: topaz-pivot

  topaz:
    image: topaztechnology/topaz:latest
    hostname: topaz
    restart: always
    mem_limit: 6gb
    ports:
    - 9021:9021    # Getdown port
    - 26634:26634  # Topaz server port
    # Uncomment to expost REPL port locally
    #- 127.0.0.1:26636:26636
    volumes:
    - topaz-conf:/opt/topaz/conf
    - topaz-data:/opt/topaz/data
    - topaz-log:/opt/topaz/log
    - topaz-shared:/opt/topaz/tmp
    environment:
      LOG_LEVEL: INFO
      DISABLE_GC_LOGGING: 1
      TOPAZ_START_ARGS: com.topaz.server.Main
      AKKA_DISCOVERY_TYPE: config
      JVM_NAME: Seed
      # Set first time only using bin/create-password-hash.sh. Remember to quote and replace $ with $$
      # This example has a password of "root" and must be changed
      ROOT_PASSWORD_HASH: "$$2a$$12$$FMN3DQ5DeF06gLw/yb3WsegCTSExXb34g6mdLp8ctD6GaKK80VvpO"
      # Set this initially here or in config and never change.
      # This example hashing pepper must be changed
      PASSWORD_HASHING_PEPPER: "pepper"
    depends_on:
    - sqlserver
    - redis
    - monet

  topaz-compute-1:
    image: topaztechnology/topaz:latest
    hostname: topaz-compute-1
    restart: always
    mem_limit: 6gb
    volumes:
      - topaz-conf:/opt/topaz/conf
      - topaz-log:/opt/topaz/log
    environment:
      TOPAZ_START_ARGS: com.topaz.server.ComputeMain
      AKKA_DISCOVERY_TYPE: config
      JVM_NAME: Compute-1
    depends_on:
      - topaz

  topaz-compute-2:
    image: topaztechnology/topaz:latest
    hostname: topaz-compute-2
    restart: always
    mem_limit: 6gb
    volumes:
      - topaz-conf:/opt/topaz/conf
      - topaz-log:/opt/topaz/log
    environment:
      TOPAZ_START_ARGS: com.topaz.server.ComputeMain
      AKKA_DISCOVERY_TYPE: config
      JVM_NAME: Compute-2
    depends_on:
      - topaz

volumes:
  sqlserver-data:
  redis-data:
  monet-data:
  topaz-data:
  topaz-log:
  topaz-shared:
  topaz-conf:
    external: true
