version: '3'

services:
  sqlserver:
    image: topaztechnology/mssql-server-linux:2017-CU9
    hostname: sqlserver
    restart: always
    ports:
    - 1433:1433
    volumes:
    - sqlserver-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SQL_USER: topaz
      SQL_PASSWORD: topaz
      SQL_DB: TopazMain

  redis:
    image: topaztechnology/redis:4.0.2
    hostname: redis
    restart: always
    ports:
    - 6379:6379
    volumes:
    - redis-data:/redis/data
    environment:
      LOG_LEVEL: INFO
      REDIS_TYPE: server

  monet:
    image: topaztechnology/monet:11.27.5
    hostname: monet
    restart: always
    ports:
    - 50000:50000
    volumes:
    - monet-data:/var/lib/monetdb
    - topaz-shared:/opt/topaz/tmp
    environment:
      LOG_LEVEL: INFO
      MONET_DATABASE: topaz-pivot

  topaz:
    image: topaztechnology/topaz:1.4.8
    hostname: topaz
    restart: always
    ports:
    - 9021:9021
    - 127.0.0.1:26630:26630
    - 26634:26634
    - 26635:26635
    - 127.0.0.1:26636:26636
    volumes:
    - topaz-conf:/opt/topaz/conf
    - topaz-data:/opt/topaz/data
    - topaz-log:/opt/topaz/log
    - topaz-shared:/opt/topaz/tmp
    - /etc:/opt/topaz/conf/host-etc
    environment:
      LOG_LEVEL: DEBUG
      BACKEND_DB_TYPE: sqlserver
      BACKEND_TICK_DB_TYPE: redis
      PIVOT_DB_TYPE: monet
      MONET_BULK_LOAD_DIR: /opt/topaz/tmp
      JAVA_DEBUG: 1
      JAVA_DEBUG_PORT: 26630
    depends_on:
    - sqlserver
    - redis
    - monet

volumes:
  sqlserver-data:
  redis-data:
  monet-data:
  topaz-data:
  topaz-log:
  topaz-shared:
  topaz-conf:
    external: true
